import type { Language } from "./i18n";
export type Localized<T> = Record<Language, T>;

const partners = [
  "/combany/logo-1.png",
  "/combany/logo-2.png",
  "/combany/logo-3.png",
  "/combany/logo-4.png",
  "/combany/logo-5.png",
  "/combany/logo-6.png",
  "/combany/logo-7.png",
  "/combany/logo-8.png",
];
export const contact = {
  whatsapp: "+963937409397",
  phones: ["+963937409397", "+963 944 000 000"],
  email: "care@prosthetics-center.com",
  hours: "09:00 - 18:00",
  maps: {
    coast: "https://maps.google.com/?q=Latakia+Syria",
    aleppo: "https://maps.google.com/?q=Aleppo+Syria",
  },
};

export const content = {
  ar: {
    seo: {
      home: "برستيل للأطراف الصناعية | حلول حركة وتأهيل متقدمة",
      about: "من نحن | برستيل للأطراف الصناعية",
      contact: "التواصل | برستيل للأطراف الصناعية",
      coast: "مركز الساحل | برستيل للأطراف الصناعية",
      aleppo: "مركز حلب | برستيل للأطراف الصناعية",
      description: "مركز متخصص في الأطراف الصناعية، العلاج الفيزيائي، أجهزة التقويم، والاندماج العظمي بخبرة إنسانية وتقنيات حديثة.",
    },
    home: {
      badge: "رعاية طبية متخصصة بالحركة",
      heroNote: "من الاستشارة الأولى حتى التأهيل، نرافق المريض بخطة واضحة وطرف مناسب لحياته اليومية.",
      partnersTitle: "شركاء وتقنيات نثق بها",
      partnersSubtitle: "نعمل مع منظومة عالمية من الشركات والمورّدين لتوفير حلول آمنة ومتطورة.",
      formTitle: "نموذج الاستشارة",
      formSubtitle: "املأ البيانات الأساسية وسيتم فتح واتساب برسالة جاهزة تحتوي كل التفاصيل.",
      trustTitle: "معاير التمييز",
      prostheticsTitle: "أنواع الأطراف الصناعية",
      testimonialsTitle: "ماذا قال مستخدمو الأطراف الاصطناعية؟",
      subtitle:"تعليقات المستخدمين عن مراكزنا",
      centersTitle: "مراكزنا وخدماتنا",
    },
    labels: {
      manufacturer: "الشركة المصنعة",
      weight: "الوزن",
      modernity: "درجة الحداثة",
      safety: "الأمان",
      benefits: "الميزات",
      why: "لماذا نستخدمها",
      duration: "مدة العلاج",
      more: "معلومات إضافية",
      whenPossible: "متى يمكن التركيب",
      conditions: "الشروط اللازمة",
      notPossible: "متى لا يمكن",
    },
    stats: ["+5000 مريض", "+29 سنوات خبرة", "تدريب طلاب +300", "+25 دول عملنا بها"],
    partners, 
    prostheticTypes: [
      ["الساق الاصطناعية", "نقدم لكم أفضل العلامات التجارية لعلاج الساق الاصطناعية أسفل وفوق الركبة بأسعار معقولة"],
      [" الذراع الاصطناعية", "نلبي احتياجات الذراع الصناعية لمرضانا من خلال الأذرع الصناعية الإلكترونية والبيونك، والتي لا تختلف عن اليد الحقيقية"],
      ["الأطراف من السيليكون", "نقوم بتصنيع الأطراف التي تتطلب تفاصيل دقيقة مثل اليدين, القدمين و الأصابع بنسبة تشابه تصل إلى 98%"],
      ["أجهزة تقويم العظام", "نحن نقدم أجهزة تقويم العظام التي تدعم مرضانا في أنشطة مثل المشي وتصحيح الوضعية"],
    ],
    testimonials: [
      ["أحمد", "بعد التأهيل شعرت أنني أستعيد تفاصيل حياتي اليومية بثقة أكبر."],
      ["سارة", "الفريق شرح كل خطوة بوضوح، وكان اختيار الطرف مناسبًا جدًا لعملي."],
      ["محمد", "الخدمة إنسانية ومنظمة، والمتابعة بعد التركيب صنعت فرقًا كبيرًا."],
    ],
    centers: {
      coast: {
        name: "مركز الساحل",
        intro: "مركز متخصص يقدم حلول الأطراف والتأهيل ضمن بيئة هادئة قريبة من المريض.",
        address: "الساحل السوري",
      },
      aleppo: {
        name: "مركز حلب",
        intro: "مركز متقدم يجمع بين الأطراف الصناعية والعلاج الفيزيائي وخدمات الاندماج العظمي.",
        address: "حلب، سوريا",
      },
    },
    services: [
      ["الأطراف الصناعية", "حلول متطورة تساعدك على استعادة الحركة بثبات وراحة."],
      ["العلاج الفيزيائي", "برامج تأهيل لتحسين الحركة وتقليل الألم بعد التركيب."],
      ["أجهزة التقويم", "أجهزة مساعدة لدعم الحركة والاستقرار في الحياة اليومية."],
    ],
    tabs: ["طرف سفلي", "طرف علوي", "طرف رياضي", "طرف تجميلي"],
    therapyTitle: "طرق العلاج الفيزيائي",
    devicesTitle: "الأجهزة والتقنيات",
    osseoTitle: "الاندماج العظمي",
    osseoSubtitle: "قصص حالات توضّح متى يكون الحل مناسبًا وكيف يتم التفكير بالأمان والتأهيل.",
    operationRulesTitle: "شروط وموانع العملية",
    conditionsTitle: "شروط إجراء العملية",
    contraindicationsTitle: "موانع إجراء العملية",
    about: {
      title: "من نحن",
      description: "برستيل مركز متخصص في الأطراف الصناعية والتأهيل، يربط بين الخبرة الطبية والتقنيات الحديثة ليمنح كل مريض خطة تناسب جسمه وحياته وطموحه.",
      mission: "مهمتنا",
      missionText: "تقديم حلول حركة آمنة ومريحة تساند المريض جسديًا ونفسيًا منذ الاستشارة وحتى المتابعة.",
      vision: "رؤيتنا",
      visionText: "أن نكون مرجعًا إقليميًا في الأطراف الصناعية الذكية والتأهيل الإنساني المتكامل.",
      why: "لماذا نحن",
      points: ["تقييم فردي لكل حالة", "تقنيات من شركات عالمية", "تأهيل ومتابعة بعد التركيب", "فريق متعدد الاختصاصات"],
    },
    contactPage: {
      title: "تواصل معنا",
      subtitle: "اختر المركز الأقرب لك أو ابدأ محادثة واتساب مباشرة للحصول على استشارة أولية.",
      phone: "أرقام الهاتف",
      locations: "المواقع",
      hours: "ساعات العمل",
      social: "القنوات الاجتماعية",
    },
  },
  en: {
    seo: {
      home: "Prosthetics Center | Advanced Mobility and Rehabilitation",
      about: "About | Prosthetics Center",
      contact: "Contact | Prosthetics Center",
      coast: "Coast Center | Prosthetics Center",
      aleppo: "Aleppo Center | Prosthetics Center",
      description: "Specialized prosthetics, physical therapy, orthotics, and osseointegration care with humane expertise and modern technology.",
    },
    home: {
      badge: "Specialized mobility care",
      heroNote: "From the first consultation to rehabilitation, we guide each patient with a clear plan and a limb suited to daily life.",
      partnersTitle: "Trusted partners and technologies",
      partnersSubtitle: "We work with a global ecosystem of companies and suppliers to provide safe, advanced solutions.",
      formTitle: "Consultation form",
      formSubtitle: "Enter the essentials and WhatsApp will open with a ready message containing every detail.",
      trustTitle: "Standards of Excellence",
      prostheticsTitle: "Types of prosthetics",
      testimonialsTitle: "What Do Our Patients Say?",
      subtitle:"User Feedback on Our Centers",
      centersTitle: "Our centers and services",
    },
    labels: {
      manufacturer: "Manufacturer",
      weight: "Weight",
      modernity: "Modernity",
      safety: "Safety",
      benefits: "Benefits",
      why: "Why we use it",
      duration: "Treatment duration",
      more: "Additional information",
      whenPossible: "When fitting is possible",
      conditions: "Required conditions",
      notPossible: "When it is not possible",
    },
stats: ["+5000 Patients", "+29 Years of Experience", "+300 Students Trained", "+25 Countries Served"],
    partners ,
    prostheticTypes: [
  ["Prosthetic Leg", "We provide top international brands for below-knee and above-knee prosthetic solutions at affordable prices."],
  ["Prosthetic Arm", "We meet our patients’ needs with advanced electronic and bionic arms that closely mimic the natural hand."],
  ["Silicone Prosthetics", "We manufacture highly detailed prosthetics such as hands, feet, and fingers with up to 98% realism."],
  ["Orthotic Devices", "We offer orthotic devices that support patients in activities such as walking and posture correction."],
],
    testimonials: [
      ["Ahmad", "After rehabilitation, I felt I was getting the small details of daily life back."],
      ["Sara", "The team explained every step clearly and the limb matched my work very well."],
      ["Mohammad", "Human service, organized follow-up, and a big difference after fitting."],
    ],
    centers: {
      coast: { name: "Coast Center", intro: "A specialized center offering prosthetics and rehabilitation in a calm, patient-first environment.", address: "Syrian Coast" },
      aleppo: { name: "Aleppo Center", intro: "An advanced center combining prosthetics, physical therapy, orthotics, and osseointegration services.", address: "Aleppo, Syria" },
    },
    services: [
      ["Prosthetics", "Advanced solutions that help restore movement with stability and comfort."],
      ["Physical therapy", "Rehabilitation programs to improve movement and reduce pain after fitting."],
      ["Orthotic devices", "Assistive devices that support movement and daily stability."],
    ],
    tabs: ["Lower limb", "Upper limb", "Sports limb", "Cosmetic limb"],
    therapyTitle: "Physical therapy methods",
    devicesTitle: "Devices and technologies",
    osseoTitle: "Osseointegration",
    osseoSubtitle: "Patient stories that explain when the solution fits and how safety and rehabilitation are considered.",
    operationRulesTitle: "Operation conditions and contraindications",
    conditionsTitle: "Required conditions",
    contraindicationsTitle: "Contraindications",
    about: {
      title: "About us",
      description: "Prosthetics Center connects clinical expertise with modern technology to give each patient a plan that fits their body, life, and ambitions.",
      mission: "Mission",
      missionText: "Deliver safe, comfortable mobility solutions that support the patient physically and emotionally from consultation to follow-up.",
      vision: "Vision",
      visionText: "To become a regional reference for intelligent prosthetics and humane integrated rehabilitation.",
      why: "Why us",
      points: ["Individual assessment for every case", "Technologies from global companies", "Rehabilitation and follow-up after fitting", "Multidisciplinary team"],
    },
    contactPage: {
      title: "Contact us",
      subtitle: "Choose the closest center or start a direct WhatsApp conversation for an initial consultation.",
      phone: "Phone numbers",
      locations: "Locations",
      hours: "Working hours",
      social: "Social channels",
    },
  },
  tr: {
    seo: {
      home: "Protez Merkezi | Gelişmiş Hareket ve Rehabilitasyon",
      about: "Hakkımızda | Protez Merkezi",
      contact: "İletişim | Protez Merkezi",
      coast: "Sahil Merkezi | Protez Merkezi",
      aleppo: "Halep Merkezi | Protez Merkezi",
      description: "İnsani uzmanlık ve modern teknolojiyle protez, fizik tedavi, ortez ve osseointegrasyon hizmetleri.",
    },
    home: {
      badge: "Uzman hareket bakımı",
      heroNote: "İlk danışmanlıktan rehabilitasyona kadar her hastaya günlük yaşama uygun net bir planla eşlik ederiz.",
      partnersTitle: "Güvenilir ortaklar ve teknolojiler",
      partnersSubtitle: "Güvenli ve gelişmiş çözümler için küresel şirketler ve tedarikçilerle çalışıyoruz.",
      formTitle: "Danışmanlık formu",
      formSubtitle: "Temel bilgileri girin; WhatsApp tüm detayları içeren hazır bir mesajla açılsın.",
      trustTitle: "Mükemmellik Standartları",
      prostheticsTitle: "Protez türleri",
      testimonialsTitle: "Protez Kullanıcıları Ne Diyor?",
      subtitle:"Merkezlerimiz Hakkında Kullanıcı Yorumları",
      centersTitle: "Merkezlerimiz ve hizmetlerimiz",
    },
    labels: {
      manufacturer: "Üretici",
      weight: "Ağırlık",
      modernity: "Teknoloji düzeyi",
      safety: "Güvenlik",
      benefits: "Faydalar",
      why: "Neden kullanılır",
      duration: "Tedavi süresi",
      more: "Ek bilgi",
      whenPossible: "Ne zaman uygulanabilir",
      conditions: "Gerekli koşullar",
      notPossible: "Ne zaman uygulanamaz",
    },
stats: ["+5000 Hasta", "+29 Yıl Deneyim", "+300 Öğrenci Eğitildi", "+25 Ülkede Hizmet"],
    partners ,
    prostheticTypes: [
  ["Protez Bacak", "Diz altı ve diz üstü protez çözümleri için en iyi uluslararası markaları uygun fiyatlarla sunuyoruz."],
  ["Protez Kol", "Hastalarımızın ihtiyaçlarını, gerçek ele çok yakın olan gelişmiş elektronik ve biyonik kollarla karşılıyoruz."],
  ["Silikon Protezler", "El, ayak ve parmak gibi detay gerektiren protezleri %98’e varan gerçekçilikle üretiyoruz."],
  ["Ortez Cihazları", "Yürüme ve duruş düzeltme gibi aktivitelerde hastalarımıza destek olan ortez cihazları sunuyoruz."],
],
    testimonials: [
      ["Ahmad", "Rehabilitasyondan sonra günlük hayatın küçük detaylarını geri kazandığımı hissettim."],
      ["Sara", "Ekip her adımı açıkça anlattı ve protez işime çok uygun oldu."],
      ["Mohammad", "İnsani hizmet, düzenli takip ve uygulama sonrası büyük fark."],
    ],
    centers: {
      coast: { name: "Sahil Merkezi", intro: "Sakin ve hasta odaklı bir ortamda protez ve rehabilitasyon sunan uzman merkez.", address: "Suriye Sahili" },
      aleppo: { name: "Halep Merkezi", intro: "Protez, fizik tedavi, ortez ve osseointegrasyon hizmetlerini birleştiren gelişmiş merkez.", address: "Halep, Suriye" },
    },
    services: [
      ["Protezler", "Hareketi denge ve konforla geri kazanmaya yardımcı gelişmiş çözümler."],
      ["Fizik tedavi", "Uygulama sonrası hareketi iyileştiren ve ağrıyı azaltan programlar."],
      ["Ortez cihazları", "Günlük hareket ve dengeyi destekleyen yardımcı cihazlar."],
    ],
    tabs: ["Alt ekstremite", "Üst ekstremite", "Spor protezi", "Kozmetik protez"],
    therapyTitle: "Fizik tedavi yöntemleri",
    devicesTitle: "Cihazlar ve teknolojiler",
    osseoTitle: "Osseointegrasyon",
    osseoSubtitle: "Çözümün ne zaman uygun olduğunu, güvenlik ve rehabilitasyonun nasıl değerlendirildiğini anlatan hasta hikayeleri.",
    operationRulesTitle: "Operasyon koşulları ve engeller",
    conditionsTitle: "Gerekli koşullar",
    contraindicationsTitle: "Kontrendikasyonlar",
    about: {
      title: "Hakkımızda",
      description: "Protez Merkezi, her hastaya bedenine, hayatına ve hedeflerine uygun bir plan sunmak için klinik uzmanlığı modern teknolojiyle birleştirir.",
      mission: "Misyonumuz",
      missionText: "Danışmanlıktan takibe kadar hastayı fiziksel ve duygusal olarak destekleyen güvenli, konforlu hareket çözümleri sunmak.",
      vision: "Vizyonumuz",
      visionText: "Akıllı protezler ve insani entegre rehabilitasyonda bölgesel referans olmak.",
      why: "Neden biz",
      points: ["Her vaka için bireysel değerlendirme", "Küresel şirketlerden teknolojiler", "Uygulama sonrası rehabilitasyon ve takip", "Çok disiplinli ekip"],
    },
    contactPage: {
      title: "İletişim",
      subtitle: "Size en yakın merkezi seçin veya ilk danışmanlık için doğrudan WhatsApp konuşması başlatın.",
      phone: "Telefon numaraları",
      locations: "Konumlar",
      hours: "Çalışma saatleri",
      social: "Sosyal kanallar",
    },
  },
} satisfies Localized<any>;

export const prostheticPosts = Array.from({ length: 48 }, (_, index) => ({
  id: index + 1,
  tab: index % 4,
  title: {
    ar: ["ركبة ذكية", "قدم كربونية", "يد وظيفية", "طرف تجميلي"][index % 4] + ` ${Math.floor(index / 4) + 1}`,
    en: ["Smart knee", "Carbon foot", "Functional hand", "Cosmetic limb"][index % 4] + ` ${Math.floor(index / 4) + 1}`,
    tr: ["Akıllı diz", "Karbon ayak", "Fonksiyonel el", "Kozmetik protez"][index % 4] + ` ${Math.floor(index / 4) + 1}`,
  },
  description: {
    ar: "طرف مصمم للتوازن والراحة مع خيارات ضبط تناسب نمط حياة المريض.",
    en: "A limb designed for balance and comfort with fitting options for the patient's lifestyle.",
    tr: "Hastanın yaşam tarzına uygun ayar seçenekleriyle denge ve konfor için tasarlanmış protez.",
  },
  manufacturer: ["Ottobock", "Össur", "Blatchford", "Fillauer"][index % 4],
  weight: ["750g", "980g", "1.2kg", "620g"][index % 4],
  modernity: ["Microprocessor", "Carbon dynamic", "Myoelectric", "Silicone finish"][index % 4],
  safety: ["High", "High", "Medium-high", "Daily use" ][index % 4],
}));

export const therapyMethods = [
  {
    title: { ar: "تدريب المشي", en: "Gait training", tr: "Yürüme eğitimi" },
    description: { ar: "إعادة تعليم الجسم على خطوات متوازنة وآمنة بعد تركيب الطرف.", en: "Retraining the body for balanced, safe steps after fitting.", tr: "Uygulama sonrası dengeli ve güvenli adımlar için vücudu yeniden eğitme." },
    why: { ar: "لتحسين الثبات وتقليل التعويضات الحركية.", en: "To improve stability and reduce compensatory movement.", tr: "Dengeyi artırmak ve telafi hareketlerini azaltmak için." },
    duration: { ar: "من 4 إلى 8 أسابيع حسب الحالة.", en: "4 to 8 weeks depending on the case.", tr: "Vakaya göre 4 ila 8 hafta." },
  },
  {
    title: { ar: "تقوية العضلات", en: "Muscle strengthening", tr: "Kas güçlendirme" },
    description: { ar: "تمارين موجهة للعضلات الداعمة للحوض والركبة والكتف.", en: "Targeted exercises for supporting hip, knee, and shoulder muscles.", tr: "Kalça, diz ve omuz destek kaslarına yönelik egzersizler." },
    why: { ar: "لزيادة تحمل الطرف وتقليل الألم.", en: "To increase limb tolerance and reduce pain.", tr: "Protez toleransını artırmak ve ağrıyı azaltmak için." },
    duration: { ar: "جلسات متدرجة خلال خطة التأهيل.", en: "Progressive sessions throughout rehabilitation.", tr: "Rehabilitasyon boyunca kademeli seanslar." },
  },
  {
    title: { ar: "العلاج الوظيفي", en: "Functional therapy", tr: "Fonksiyonel terapi" },
    description: { ar: "تطبيق مهارات الحياة اليومية مثل الصعود والجلوس واستخدام اليد.", en: "Practicing daily skills such as stairs, sitting, and hand use.", tr: "Merdiven, oturma ve el kullanımı gibi günlük becerilerin çalışılması." },
    why: { ar: "لتحويل الطرف من جهاز إلى جزء من الروتين اليومي.", en: "To turn the limb from a device into part of daily routine.", tr: "Protezi cihaz olmaktan çıkarıp günlük rutinin parçası yapmak için." },
    duration: { ar: "حسب هدف المريض ونوع الطرف.", en: "Based on patient goals and limb type.", tr: "Hasta hedeflerine ve protez türüne göre." },
  },
];

export const devices = [
  {
    title: { ar: "جهاز تحليل المشي", en: "Gait analysis system", tr: "Yürüme analiz sistemi" },
    description: { ar: "يساعد الفريق على فهم توزيع الوزن وخطوة المريض قبل ضبط الطرف.", en: "Helps the team understand weight distribution and the patient's step before tuning.", tr: "Ekibin ayar öncesi ağırlık dağılımını ve adımı anlamasına yardımcı olur." },
    benefits: { ar: ["ضبط أدق", "تقليل الضغط", "قياس موضوعي"], en: ["More precise fitting", "Reduced pressure", "Objective measurement"], tr: ["Daha hassas uyum", "Azaltılmış basınç", "Objektif ölçüm"] },
  },
  {
    title: { ar: "وحدة التوازن", en: "Balance unit", tr: "Denge ünitesi" },
    description: { ar: "تدريب آمن لتحسين الثبات والثقة أثناء الوقوف والمشي.", en: "Safe training to improve stability and confidence while standing and walking.", tr: "Ayakta durma ve yürümede denge ve güveni artıran güvenli eğitim." },
    benefits: { ar: ["ثبات أعلى", "أمان أثناء التدريب", "متابعة التقدم"], en: ["Higher stability", "Safe training", "Progress tracking"], tr: ["Daha yüksek denge", "Güvenli eğitim", "İlerleme takibi"] },
  },
  {
    title: { ar: "معدات التقويم", en: "Orthotic workshop tools", tr: "Ortez atölye araçları" },
    description: { ar: "أجهزة تشكيل وتجهيز تساعد على إنتاج داعم مريح ومناسب للحالة.", en: "Forming and preparation equipment for comfortable supportive devices.", tr: "Konforlu destek cihazları için şekillendirme ve hazırlık ekipmanları." },
    benefits: { ar: ["راحة أفضل", "دعم مخصص", "مواد آمنة"], en: ["Better comfort", "Custom support", "Safe materials"], tr: ["Daha iyi konfor", "Özel destek", "Güvenli malzemeler"] },
  },
];

export const osseoCases = [
  {
    title: { ar: "حالة بتر تحت الركبة", en: "Below-knee amputation case", tr: "Diz altı amputasyon vakası" },
    description: { ar: "تم تركيب طرف متطور يمنح اتصالًا مباشرًا أكثر ثباتًا بالحركة اليومية.", en: "An advanced limb was fitted to provide a more stable direct connection for daily movement.", tr: "Günlük hareket için daha stabil doğrudan bağlantı sağlayan gelişmiş protez uygulandı." },
    whenPossible: { ar: "بعد التئام الجرح بشكل كامل وتقييم العظم.", en: "After full wound healing and bone assessment.", tr: "Yara tamamen iyileştikten ve kemik değerlendirildikten sonra." },
    conditions: { ar: "صحة عامة جيدة، عظم مناسب، والتزام بالتأهيل.", en: "Good general health, suitable bone, and commitment to rehabilitation.", tr: "İyi genel sağlık, uygun kemik ve rehabilitasyona bağlılık." },
    notPossible: { ar: "التهابات نشطة أو ضعف شديد في العظم.", en: "Active infections or severe bone weakness.", tr: "Aktif enfeksiyon veya ciddi kemik zayıflığı." },
    safety: { ar: "نسبة أمان عالية عند الالتزام بالشروط.", en: "High safety when conditions are respected.", tr: "Koşullara uyulduğunda yüksek güvenlik." },
  },
  {
    title: { ar: "حالة بتر فوق الركبة", en: "Above-knee amputation case", tr: "Diz üstü amputasyon vakası" },
    description: { ar: "خطة تدريجية تجمع بين التقييم الجراحي والتأهيل لضمان استخدام آمن.", en: "A gradual plan combining surgical assessment and rehabilitation for safe use.", tr: "Güvenli kullanım için cerrahi değerlendirme ve rehabilitasyonu birleştiren kademeli plan." },
    whenPossible: { ar: "بعد تقييم الفريق المختص واستقرار الحالة العامة.", en: "After specialist assessment and general condition stability.", tr: "Uzman değerlendirmesi ve genel durum stabilitesinden sonra." },
    conditions: { ar: "لا توجد التهابات، جودة عظم مناسبة، ودعم علاجي مستمر.", en: "No infections, suitable bone quality, and ongoing therapeutic support.", tr: "Enfeksiyon olmaması, uygun kemik kalitesi ve sürekli tedavi desteği." },
    notPossible: { ar: "أمراض مزمنة غير مستقرة أو عدم القدرة على التأهيل.", en: "Unstable chronic disease or inability to rehabilitate.", tr: "Stabil olmayan kronik hastalık veya rehabilitasyon yetersizliği." },
    safety: { ar: "تتم المتابعة على مراحل لتقليل المخاطر.", en: "Follow-up happens in stages to reduce risk.", tr: "Riski azaltmak için takip aşamalı yapılır." },
  },
];

export const operationConditions = {
  good: {
    ar: ["صحة عامة جيدة", "عدم وجود التهابات", "جودة عظم مناسبة", "التزام المريض بالعلاج"],
    en: ["Good general health", "No infections", "Suitable bone quality", "Commitment to therapy"],
    tr: ["İyi genel sağlık", "Enfeksiyon olmaması", "Uygun kemik kalitesi", "Tedaviye bağlılık"],
  },
  bad: {
    ar: ["أمراض مزمنة غير مستقرة", "ضعف شديد في العظام", "التهابات نشطة", "عدم القدرة على التأهيل"],
    en: ["Unstable chronic disease", "Severe bone weakness", "Active infections", "Inability to rehabilitate"],
    tr: ["Stabil olmayan kronik hastalık", "Ciddi kemik zayıflığı", "Aktif enfeksiyon", "Rehabilitasyon yetersizliği"],
  },
};
